### ISSUE TITLE
Perl 5.22.1: Unescaped left brace in regex is deprecated

### ISSUE THREAD

**Issue by bgainor** [robinbowes/flac2mp3#47]
On running flac2mp3.pl (v1.0.0) in my system, I get the following warning:

```
$ flac2mp3 -h
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(\\%(?:\\=)?(\w|\\{ <-- HERE (?:\w|\\[^\w\\{}]|\\\\\\[\\{}])*\\}|\\\W))/ at /usr/local/lib/flac2mp3-1.0.0/lib/MP3/Tag.pm line 2611.
Usage: /usr/local/bin/flac2mp3 <options> <flacdir> <mp3dir>
…
```

It seems like it's just a warning, as the rest of the `-h` option seems to execute normally. I have Perl v5.22.1 installed.

**Comment by robinbowes** [comment]
This is/was a warning from MP3::Tag. I've upgraded to the latest version from Sept 2016 so I think this should now be fixed (upgrade to latest flac2mp3 from master branch).
