### ISSUE TITLE
Unescaped left brace in regex is deprecated

### ISSUE THREAD

**Issue by derekhendrickx** [robinbowes/flac2mp3#51]
Everytime I run the script I got this warning:

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(\\%(?:\\=)?(\w|\\{ <-- HERE (?:\w|\\[^\w\\{}]|\\\\\\[\\{}])*\\}|\\\W))/ at /usr/lib64/perl5/vendor_perl/5.22.3/MP3/Tag.pm line 2611.
```

**Comment by robinbowes** [comment]
That warning is from the MP3::Tag module which you have installed separately to flac2mp3. You could try upgrading it, or deleting it and using the one bundled with flac2mp3.
