### ISSUE TITLE
flac not found at flac2mp3.pl line 228

### ISSUE THREAD

**Issue by erikparr** [robinbowes/flac2mp3#52]
When run the script i get a flac not found error, despite the fact that my paths are definitely pointing to valid directories filled with flac files. Whats going on here?
`perl flac2mp3.pl /path/to/lossless /path/to/lossy `(replaced with actual file paths of course)
returns
`flac not found at flac2mp3.pl line 228`
on macos sierra
thx

**Comment by robinbowes** [comment]
That's telling you you've not got the flac tool installed.

Install flac.

**Comment by erikparr** [comment]
Right. that did the trick. thanks
