### ISSUE TITLE
Unescaped left brace in regex is deprecated here ...

### ISSUE THREAD

**Issue by mindonly** [robinbowes/flac2mp3#56]
i'm sorry to raise this again, but i would like to suggest that flac2mp3 be updated to ship MP3::Tag 1.15 to address the "unescaped left brace" messages that are still appearing.

i know that issues #47 and #51 already mentioned and addressed this symptom, but i'm still seeing these on macos with perl v5.30.1 and the latest flac2mp3:

> Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/^\??({ <-- HERE ([^{}]+)}|.)/ at /Users/mindonly/dev/flac2mp3/lib/MP3/Tag.pm line 3080.
> Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/^({ <-- HERE [^{}]+}|\w)/ at /Users/mindonly/dev/flac2mp3/lib/MP3/Tag.pm line 3092.

currently flac2mp3 ships MP3::Tag 1.14, but version 1.15 addresses unescaped braces specifically. from the [MP3::Tag Changes file](https://metacpan.org/source/ILYAZ/MP3-Tag-1.15/Changes):

> Release Name: 1.15
> ====================
>  
> Tag.pm: Fix more unescaped-{ warnings (thanks to Christian Walde etc).

i was able to fix this on my system by installing v1.15 separately and adding a 'use lib' statement to point to my local MP3::Tag 1.15 in flac2mp3.pl. this is fine for my purposes but it would probably be cleaner to just ship v1.15 with flac2mp3.

just a suggestion!

**Comment by robinbowes** [comment]
Thanks, I'll try and sort that soon.
